version: "3"

services:
  database:
    image: postgres:16.0-bookworm
    container_name: simbirgo-postgres
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=simbirgo
      - POSTGRES_USER=simbirgo
      - POSTGRES_PASSWORD=simbirgo
    ports:
      - "7999:5432"
    networks:
      - simbirgo-network
    restart: always

networks:
  simbirgo-network:
    name:
      - simbirgo-network
    external: true
