"""init migration

Revision ID: 5e98ab3bdbdc
Revises: 
Create Date: 2023-10-31 23:04:13.765494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e98ab3bdbdc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('isAdmin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('balance', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('transports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canBeRented', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('transportType', sa.Enum('CAR', 'BIKE', 'SCOOTER', name='transporttypeenum'), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('longitude', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('minutePrice', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('dayPrice', sa.Float(), server_default='0.0', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transportId', sa.Uuid(), nullable=False),
    sa.Column('userId', sa.Uuid(), nullable=False),
    sa.Column('timeStart', sa.DateTime(), nullable=False),
    sa.Column('timeEnd', sa.DateTime(), nullable=True),
    sa.Column('priceOfUnit', sa.Float(), nullable=False),
    sa.Column('priceType', sa.Enum('MINUTES', 'DAYS', name='rentpriceenum'), nullable=False),
    sa.Column('finalPrice', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['transportId'], ['transports.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rents')
    op.drop_table('transports')
    op.drop_table('users')
    # ### end Alembic commands ###
